#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

app_lucky_cometidonacionales:
    path: /lucky/cometidonacionales
    controller: App\Controller\LuckyController::cometidonacionales

app_lucky_cometido:
    path: /lucky/cometido
    controller: App\Controller\LuckyController::cometido

app_PdfCometidoNacional:
    path: /pdf/show
    controller: App\Controller\PdfController::PdfCometidoNacional

app_controller:
    path: /get
    controller: App\Controller\Controller::tramitar_validar_pago_viatico_save

app_devengar:
    path: /devengar
    controller: App\Controller\Controller::tramitar_devengar_pago_viatico_save
